### ISSUE TITLE
badge: add icons to badges, add white color badge

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system-assets#11]
![image](https://user-images.githubusercontent.com/3674406/42716360-f6241744-86af-11e8-939f-dc871c4100c3.png)
![image](https://user-images.githubusercontent.com/3674406/42716371-040107c8-86b0-11e8-9ef2-655ba57a2c0b.png)

**Comment by colequartootcha** [comment]
Added Icon White Badge in 18f4218

**Comment by dborodyansky** [comment]
Thank you @colequartootcha !
